version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    ports:
      - "11433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@Anhcuto3568oksex[][]"
    restart: unless-stopped

  springboot-app:
    build:
      context: ./config-docker
      dockerfile: Dockerfile
    ports:
      - "8080:9000"