version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    ports:
      - "11433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@Anhcuto3568oksex[][]"
    restart: unless-stopped
    networks:
      - my-network

  configdocker:
    image: ambrouse/configdocker:latest
    container_name: configdocker
    build:
      context: ./config_cloud_server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - my-network
    depends_on:
      - sqlserver
    restart: unless-stopped
  
  ereukadocker:
    image: ambrouse/ereukadocker:latest
    container_name: ereukadocker
    build:
      context: ./eureka_server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network
    depends_on:
      - configdocker
    restart: unless-stopped
  
  
  productservicedocker:
    image: ambrouse/productservicedocker:latest
    container_name: productservicedocker
    build:
      context: ./product_service
      dockerfile: Dockerfile
    ports:
      - "9005:9005"
    networks:
      - my-network
    depends_on:
      - ereukadocker
    restart: unless-stopped
  
  authservicedocker:
    image: ambrouse/authservicedocker:latest
    container_name: authservicedocker
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    networks:
      - my-network
    depends_on:
      - productservicedocker
    restart: unless-stopped
  
  cartservicedocker:
    image: ambrouse/cartservicedocker:latest
    container_name: cartservicedocker
    build:
      context: ./card_service
      dockerfile: Dockerfile
    ports:
      - "9006:9006"
    networks:
      - my-network
    depends_on:
      - authservicedocker
    restart: unless-stopped
  
  userservicedocker:
    image: ambrouse/userservicedocker:latest
    container_name: userservicedocker
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    networks:
      - my-network
    depends_on:
      - cartservicedocker
    restart: unless-stopped

  routerdocker:
    image: ambrouse/routerdocker:latest
    container_name: routerdocker
    build:
      context: ./router_server
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - my-network
    depends_on:
      - userservicedocker
    restart: unless-stopped

  deepservicedocker:
    image: ambrouse/deepservicedocker:latest
    container_name: deepservicedocker
    build:
      context: ./deep_service
      dockerfile: Dockerfile
    ports:
      - "9007:9007"
    depends_on:
      - routerdocker
    networks:
      - my-network
    restart: unless-stopped

  reactwebdocker:
    image: ambrouse/reactwebdocker:latest
    build:
      context: ./react_web/react_web
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - deepservicedocker
    networks:
      - my-network
    restart: unless-stopped





networks:
  my-network:
    driver: bridge